Repository wrappid/service-core, pull requests merged in 2024-03, with the labels that each got.

#91 fix(global): :bug: fix business and formshemas api
  package/modules/_system/controllers/business.controller.ts
  package/modules/_system/controllers/database.controller.ts
  package/modules/_system/functions/formSchema.helper.ts
Labels: bug

#92 bugfix: noauth/formSchema/:formID api fix
  package/modules/_system/controllers/forms.controller.ts
  package/modules/_system/functions/formSchema.helper.ts
Labels: bug

#94 fix(global): :bug: upload middleware fix
  package-lock.json
  package.json
  package/middlewares/fileHandler.middleware.ts
  package/utils/upload.utils.ts
Labels: bugfix

#96 perf(global): :sparkles: modification in app and index file
  package/app.ts
  package/index.ts
Labels: enhancement

#97 merge: Development into main
  CHANGELOG.md
  package-lock.json
  package.json
  package/app.ts
  package/index.ts
  package/middlewares/fileHandler.middleware.ts
  package/modules/_system/controllers/forms.controller.ts
  package/modules/_system/functions/formSchema.helper.ts
  package/package-lock.json
  package/package.json
  package/utils/upload.utils.ts
Labels: enhancement

#99 feat(global): :sparkles: data API added
  package/modules/_system/controllers.registry.ts
  package/modules/_system/controllers/data.controller.ts
  package/modules/_system/functions/data.function.ts
  package/modules/_system/routes.registry.ts
Labels: enhancement

#101 fix: fix version not coming
  package/utils/routes.utils.ts
Labels: enhancement

#103 feat(global): :sparkles: communication enable or disable feature added
  package/communication/communicate.communicator.ts
  package/communication/email/email.communication.ts
  package/communication/sms/sms.communication.ts
  package/communication/whatsapp/whatsapp.communication.ts
  package/config/types.config.ts
  package/utils/communication.utils.ts
Labels: enhancement

#106 enhancement: header in attribution script
  ATTRIBUTIONS.md
  scripts/attributions.gen.js
Labels: enhancement

#109 bugfix: 🐛 fix eslint pr guardrails
  .github/workflows/pr-guardrails.yml
Labels: bugfix

#110 feat(global): :sparkles: winston logging
  package-lock.json
  package.json
  package/app.ts
  package/logging/setup.logging.ts
  package/modules/_system/controllers/business.controller.ts
Labels: enhancement

#111 enhancement: create test route for communication
  package-lock.json
  package.json
  package/communication/communicate.communicator.ts
  package/communication/whatsapp/whatsapp.communication.ts
  package/modules/_system/controllers.registry.ts
  package/modules/_system/controllers/_system.controller.ts
  package/modules/_system/functions/_system.function.ts
  package/modules/_system/routes.registry.ts
  package/modules/_system/utils/_system.utils.ts
  package/modules/_system/validations/_system.validation.ts
Labels: enhancement

#112 feat(global): :wrench: update package json inside package folder
  package/package-lock.json
  package/package.json
Labels: enhancement

#114 feat(global): :zap: database action fix
  package/database/actions.database.ts
Labels: enhancement

#115 merge: Development into main
  .github/workflows/pr-guardrails.yml
  ATTRIBUTIONS.md
  CHANGELOG.md
  package-lock.json
  package.json
  package/app.ts
  package/communication/communicate.communicator.ts
  package/communication/email/email.communication.ts
  package/communication/sms/sms.communication.ts
  package/communication/whatsapp/whatsapp.communication.ts
  package/config/types.config.ts
  package/database/actions.database.ts
  package/logging/setup.logging.ts
  package/modules/_system/controllers.registry.ts
  package/modules/_system/controllers/_system.controller.ts
  package/modules/_system/controllers/business.controller.ts
  package/modules/_system/controllers/data.controller.ts
  package/modules/_system/functions/_system.function.ts
  package/modules/_system/functions/data.function.ts
  package/modules/_system/routes.registry.ts
  package/modules/_system/utils/_system.utils.ts
  package/modules/_system/validations/_system.validation.ts
  package/package-lock.json
  package/package.json
  package/route/setup.landing.route.ts
  package/utils/communication.utils.ts
  package/utils/routes.utils.ts
  scripts/attributions.gen.js
Labels: enhancement

#118 feat(global): :sparkles: masterdata api moved to service-core
  package/logging/setup.logging.ts
  package/modules/_system/controllers.registry.ts
  package/modules/_system/controllers/_system.controller.ts
  package/modules/_system/functions/_system.function.ts
  package/modules/_system/validations/_system.validation.ts
Labels: enhancement
