Repository wrappid/service-core, pull requests merged in 2024-05, with the labels that each got.

#145 feat(global): :sparkles: new test suite added
  package/testsuite/WrappaidTest.ts
Labels: enhancement

#146 Wrpd enhancement 128
  package-lock.json
  package.json
  package/WrappidApp.ts
  package/app.ts
  package/cache/cache.actions.ts
  package/cache/cache.provider.ts
  package/communication/communicate.communicator.ts
  package/communication/whatsapp/whatsapp.communication.ts
  package/config/types.config.ts
  package/constants/server.constant.ts
  package/database/actions.database.ts
  package/database/helper.database.ts
  package/database/provider.database.ts
  package/database/setup.database.ts
  package/database/setup.models.database.ts
  package/function/setup.functions.ts
  package/index.ts
  package/logging/setup.logging.ts
  package/middlewares/apiLogger.middleware.ts
  package/middlewares/jwtVerify.middleware.ts
  package/middlewares/setup.middleware.ts
  package/modules/_system/controllers.registry.ts
  package/modules/_system/controllers/business.controller.ts
  package/modules/_system/controllers/data.controller.ts
  package/modules/_system/controllers/database.controller.ts
  package/modules/_system/controllers/forms.controller.ts
  package/modules/_system/functions/_system.function.ts
  package/modules/_system/functions/businessEntity.get.helper.ts
  package/modules/_system/functions/businessEntity.helper.ts
  package/modules/_system/functions/businessEntity.post.helper.ts
  package/modules/_system/functions/data.function.ts
  package/modules/_system/functions/formSchema.helper.ts
  package/modules/_system/functions/registry.function.ts
  package/modules/_system/utils/_system.utils.ts
  package/modules/_system/validations/_system.validation.ts
  package/package-lock.json
  package/package.json
  package/payment/payment.action.ts
  package/payment/razorpay/razorpay.payment.action.ts
  package/registry/setup.registry.ts
  package/route/helper.route.ts
  package/route/setup.landing.route.ts
  package/route/setup.route.ts
  package/service/api.service.ts
  package/swagger/swagger.setup.ts
  package/tasks/setup.tasks.ts
  package/utils/communication.utils.ts
  package/utils/upload.utils.ts
Labels: enhancement

#147 chore(global): :bug: update package json with supertest/types package
  package-lock.json
  package.json
  package/package-lock.json
  package/package.json
Labels: enhancement

#148 fix(global): :bug: fix routes setup
  package-lock.json
  package.json
  package/config/provider.config.ts
  package/index.ts
  package/package-lock.json
  package/package.json
  package/registry/setup.registry.ts
Labels: enhancement

#149 enhancement: logger implementation
  package/WrappidApp.ts
  package/cache/cache.actions.ts
  package/cache/cache.provider.ts
  package/communication/communicate.communicator.ts
  package/communication/email/email.communication.ts
  package/communication/sms/sms.communication.ts
  package/context/application.context.ts
  package/database/actions.database.ts
  package/database/helper.database.ts
  package/database/setup.database.ts
  package/database/setup.models.database.ts
  package/function/setup.functions.ts
  package/logging/setup.logger.ts
  package/logging/wrappid.logger.ts
  package/middlewares/apiLogger.middleware.ts
  package/middlewares/fileHandler.middleware.ts
  package/middlewares/handleError.middleware.ts
  package/middlewares/jwtVerify.middleware.ts
  package/middlewares/setup.middleware.ts
  package/middlewares/validation.middleware.ts
  package/modules/_system/controllers/_system.controller.ts
  package/modules/_system/controllers/business.controller.ts
  package/modules/_system/controllers/data.controller.ts
  package/modules/_system/controllers/database.controller.ts
  package/modules/_system/controllers/forms.controller.ts
  package/modules/_system/controllers/registry.controller.ts
  package/modules/_system/functions/_system.function.ts
  package/modules/_system/functions/appbuilder.functions.ts
  package/modules/_system/functions/businessEntity.get.helper.ts
  package/modules/_system/functions/businessEntity.helper.ts
  package/modules/_system/functions/data.function.ts
  package/modules/_system/functions/formSchema.helper.ts
  package/modules/_system/functions/registry.function.ts
  package/modules/_system/utils/_system.utils.ts
  package/modules/_system/utils/strings.utils.ts
  package/payment/payment.action.ts
  package/payment/razorpay/razorpay.payment.action.ts
  package/registry/setup.registry.ts
  package/route/helper.route.ts
  package/route/setup.landing.route.ts
  package/route/setup.route.ts
  package/service/api.service.ts
  package/swagger/swagger.setup.ts
  package/tasks/setup.tasks.ts
  package/utils/business.utilis.ts
  package/utils/communication.utils.ts
  package/utils/routes.utils.ts
  package/utils/upload.utils.ts
Labels: enhancement

#151 fix(global): :bug: jwt validation fix
  package-lock.json
  package.json
  package/middlewares/jwtVerify.middleware.ts
Labels: bug, bugfix

#153 fix(global): :bug: read from db routes destructuring fix
  package/registry/setup.registry.ts
Labels: bug

#156 fix(core): :zap: automated swagger json title and version change from…
  package/WrappidApp.ts
  package/swagger/swagger.setup.ts
Labels: enhancement

#157 enhancement: model json to model sequelize instance creation
  package/database/Book.model.json
  package/database/ModelSchemas.model.json
  package/database/generic.model.ts
  package/database/setup.database.ts
  package/database/setup.models.database.ts
  package/index.ts
  package/models/Pages.model.ts
  package/models/model_Json/ApiRequestLogs.model.json
  package/models/model_Json/Applications.model.json
  package/models/model_Json/CommunicationHistories.model.json
  package/models/model_Json/CommunicationTemplates.model.json
  package/models/model_Json/CronSchemas.model.json
  package/models/model_Json/DataTableOptions.model.json
  package/models/model_Json/MasterData.model.json
  package/models/model_Json/Otp.model.json
  package/models/model_Json/Pages.model.json
  package/models/model_Json/Routes.model.json
  package/models/model_Json/SettingMeta.model.json
  package/models/model_Json/StringValues.model.json
  package/models/model_Json/SupportedLanguages.model.json
  package/modules/_system/functions/businessEntity.helper.ts
  package/modules/_system/models.registry.ts
  package/modules/_system/models/model_json/BusinessEntitySchemas.model.json
  package/modules/_system/models/model_json/FormSchemas.model.json
  package/modules/_system/models/model_json/ThemeSchemas.model.json
  package/registry/ModelsRegistry.ts
Labels: enhancement

#159 fix(global): :bug: fix setupmodel from database
  package/WrappidApp.ts
  package/database/setup.database.ts
  package/database/setup.models.database.ts
  package/models/model_Json/Routes.model.json
  package/modules/_system/functions/data.function.ts
Labels: enhancement

#160 fix(global): :ambulance: data clone fix
  package/database/setup.models.database.ts
  package/modules/_system/functions/data.function.ts
Labels: bugfix

#162 feat(global): :sparkles: routes registry a system field add
  package/modules/_system/functions/data.function.ts
  package/modules/_system/routes.registry.ts
Labels: enhancement

#164 feat(global): :sparkles: new API to get all databases
  package/models/Pages.model.ts
  package/models/Routes.models.ts
  package/models/model_Json/Pages.model.json
  package/models/model_Json/Routes.model.json
  package/modules/_system/controllers.registry.ts
  package/modules/_system/controllers/database.controller.ts
  package/modules/_system/functions/data.function.ts
  package/modules/_system/models/BusinessEntitySchemas.model.ts
  package/modules/_system/models/FormSchemas.model.ts
  package/modules/_system/models/ThemeSchemas.model.ts
  package/modules/_system/models/model_json/BusinessEntitySchemas.model.json
  package/modules/_system/models/model_json/FormSchemas.model.json
  package/modules/_system/models/model_json/ThemeSchemas.model.json
  package/modules/_system/routes.registry.ts
Labels: enhancement

#165 fix(global): :bug: putDatabaseModel fix
  package/modules/_system/functions/data.function.ts
Labels: enhancement

#168 ci(config): :bug: jsdoc lint issue
  .eslintrc.js
Labels: bugfix
