Repository wrappid/service-core, pull requests merged in 2024-02, with the labels that each got.

#37 fix: :ambulance: database connection fix
  package/config/provider.config.ts
  package/database/provider.database.ts
Labels: enhancement

#41 fix(utils): fix type error
  package/middlewares/fileHandler.middleware.ts
  package/utils/upload.utils.ts
Labels: bug

#43 feat: package json update
  package-lock.json
  package.json
Labels: enhancement

#45 refactor: :art: code linting fix
  .eslintrc.js
  package-lock.json
  package.json
  package/cache/cache.provider.ts
  package/communication/whatsapp/whatsapp.communication.ts
  package/config/provider.config.ts
  package/database/provider.database.ts
  package/logging/setup.logging.ts
  package/middlewares/apiLogger.middleware.ts
  package/middlewares/fileHandler.middleware.ts
  package/middlewares/handleError.middleware.ts
  package/middlewares/jwtVerify.middleware.ts
  package/modules/_system/functions/appbuilder.functions.ts
  package/package-lock.json
  package/package.json
  package/route/helper.route.ts
  package/route/setup.route.ts
  package/tasks/setup.tasks.ts
  package/utils/upload.utils.ts
Labels: enhancement

#48 fix: update package.json
  package-lock.json
  package.json
Labels: documentation

#51 enhancement: version api added to service-core
  package/index.ts
  package/modules/_system/controllers.registry.ts
  package/modules/_system/controllers/_system.controller.ts
  package/modules/_system/controllers/appbuilder.controller.ts
  package/modules/_system/routes.registry.ts
  package/registry/RoutesRegistry.ts
  package/registry/index.ts
  package/route/setup.route.ts
Labels: enhancement

#52 merge: from Development
  package/index.ts
  package/modules/_system/controllers.registry.ts
  package/modules/_system/controllers/_system.controller.ts
  package/modules/_system/controllers/appbuilder.controller.ts
  package/modules/_system/routes.registry.ts
  package/registry/RoutesRegistry.ts
  package/registry/index.ts
  package/route/setup.route.ts
Labels: enhancement

#56 enhancement: setup landing route
  package-lock.json
  package.json
  package/content/default.landing.html
  package/index.ts
  package/package-lock.json
  package/package.json
  package/route/setup.landing.route.ts
  package/route/setup.route.ts
  tsconfig.json
Labels: enhancement

#57 merge: from Development
  package-lock.json
  package.json
  package/content/default.landing.html
  package/index.ts
  package/package-lock.json
  package/package.json
  package/route/setup.landing.route.ts
  package/route/setup.route.ts
  tsconfig.json
Labels: enhancement

#58 fix(core): :bug: node-fetch package issue resolved
  package-lock.json
  package.json
  package/communication/sms/sms.communication.ts
  package/communication/whatsapp/whatsapp.communication.ts
  package/package-lock.json
  package/package.json
Labels: enhancement

#59 fix: :bug: default landing route order fix
  package/route/setup.route.ts
Labels: bug

#61 Merge development into main
  package/models/CommunicationHistory.model.ts
  package/models/CommunicationTemplates.model.ts
  package/models/Otp.model.ts
  package/modules/_system/models.registry.ts
  package/modules/_system/models/BusinessEntitySchemas.model.ts
  package/modules/_system/models/FormSchemas.model.ts
  package/modules/_system/models/Users.model.ts
  package/registry/ModelsRegistry.ts
Labels: enhancement

#63 fix: :bug: fix default landing pages
  package/route/setup.landing.route.ts
Labels: enhancement

#64 Merge development into main
  package/route/setup.landing.route.ts
Labels: enhancement

#66 fix(global): :zap: fix type missing
  package/config/types.config.ts
Labels: bug

#70 enhancement: _system all API serve from routes registry also mark status inactive those routes in DB Routes table
  package/modules/_system/controllers.registry.ts
  package/modules/_system/controllers/_system.controller.ts
  package/modules/_system/controllers/forms.controller.ts
  package/modules/_system/functions/_system.function.ts
  package/modules/_system/routes.registry.ts
  package/modules/_system/validations/_system.validation.ts
Labels: enhancement

#71 merge: main into development
  CHANGELOG.md
  package-lock.json
  package.json
  package/modules/_system/controllers.registry.ts
  package/modules/_system/controllers/_system.controller.ts
  package/modules/_system/controllers/forms.controller.ts
  package/modules/_system/functions/_system.function.ts
  package/modules/_system/routes.registry.ts
  package/modules/_system/validations/_system.validation.ts
  package/package-lock.json
  package/package.json
Labels: enhancement

#72 feat(global): :sparkles: enhancement of html content and fix year not showing
  package/content/default.landing.html
  package/route/setup.landing.route.ts
Labels: enhancement

#73 merge: development into main
  CHANGELOG.md
  package-lock.json
  package.json
  package/content/default.landing.html
  package/package-lock.json
  package/package.json
  package/route/setup.landing.route.ts
Labels: enhancement

#74 feat(global): :sparkles: database action findByPk fix
  package/database/actions.database.ts
Labels: enhancement

#78 fix(global): :bug: get table attributes API fix
  package/modules/_system/controllers/database.controller.ts
Labels: bug

#79 merge: development into main
  CHANGELOG.md
  package-lock.json
  package.json
  package/modules/_system/controllers/database.controller.ts
  package/package-lock.json
  package/package.json
Labels: bug

#81 ci(config): :bug: fix pr-guardrails eslint
  .github/workflows/pr-guardrails.yml
Labels: bugfix

#84 feat(global): :sparkles: pages model added new column
  package/models/Pages.model.ts
Labels: enhancement
